### ISSUE TITLE
throw new TypeError('listener must be a function');

### ISSUE THREAD

**Issue by molinto** [RisingStack/writing-testable-apis-the-basics#3]
cloned repos
npm install
node main.js 

sharry@bh:~/Development/Projects/writing-testable-apis-the-basics$ node main.js 

events.js:197
    throw new TypeError('listener must be a function');
    ^

TypeError: listener must be a function
    at Server.addListener (events.js:197:11)
    at new Server (_http_server.js:227:10)
    at Object.exports.createServer (http.js:44:10)
    at Object.<anonymous> (/home/sharry/Development/Projects/writing-testable-apis-the-basics/main.js:6:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

**Comment by adisun97** [comment]
Hi, i have similar problem. Is there any solution yet?

Thanks.

Adi
